# Generated by Django 5.2 on 2026-03-05 03:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Nombre de empresa', verbose_name='Nombre')),
                ('main_service', models.CharField(default='Servicio que ofrece la empresa', verbose_name='Servicio principal')),
                ('city', models.CharField(verbose_name='Ciudad')),
                ('country', models.CharField(default='Perú', verbose_name='País')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Fecha registro')),
                ('active', models.BooleanField(default=True, verbose_name='Activo/inactivo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Servicio', verbose_name='Nombre')),
                ('description', models.CharField(default='Descripción del servicio', max_length=200, verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo/inactivo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(verbose_name='Título')),
                ('description', models.TextField(null=True, verbose_name='Descripción')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso')),
                ('duration', models.IntegerField(verbose_name='Duración(días)')),
                ('project_start', models.DateField(verbose_name='Fecha de inicio')),
                ('finished_project', models.DateField(verbose_name='Fecha de entrega')),
                ('active', models.BooleanField(default=True, verbose_name='Activo/inactivo')),
                ('company', models.ForeignKey(default='Empresa', on_delete=django.db.models.deletion.SET_DEFAULT, to='presentation.company')),
                ('service', models.ForeignKey(default='Servicio', on_delete=django.db.models.deletion.SET_DEFAULT, to='presentation.service')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
