# Generated by Django 5.2 on 2026-03-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='main_service',
            field=models.CharField(verbose_name='Servicio principal'),
        ),
        migrations.AlterField(
            model_name='project',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
    ]
