# Generated by Django 5.2 on 2026-03-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_alter_project_company_alter_project_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='../static/img/home1.jpg', upload_to='proyectos/', verbose_name='Imagen'),
        ),
    ]
